apiVersion: apps/v1
kind: Deployment
metadata:
  name: qms-backend-deployement
  labels:
    app: qms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qms-backend
  template:
    metadata:
      labels:
        app: qms-backend
    spec:
      containers:
        - name: qms-backend
          image: mazeem71/bwt-testing:1.2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qms-backend-service
spec:
  selector:
    name: qms-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
