apiVersion: apps/v1
kind: Deployment
metadata:
  name: qms-frontend-deployement
  labels:
    app: qms-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qms-frontend
  template:
    metadata:
      labels:
        app: qms-frontend
    spec:
      containers:
        - name: qms-frontend
          image: mazeem71/qms-frontend:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: qms-frontend-service
spec:
  type: NodePort
  selector:
    app: qms-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
